In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
%cd drive/My\ Drive/COMP4641\ Project/final

/content/drive/My Drive/COMP4641 Project/final


In [0]:
import pandas as pd
import numpy as np
import pandas as pd
import ast
import nltk 
nltk.download('wordnet')
from nltk.corpus import wordnet 
import sklearn
from sklearn import linear_model
import matplotlib.pyplot as plt 
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import MinMaxScaler
%matplotlib inline

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


In [0]:
!pip install imbalanced-learn

In [0]:
def retrieve_csv():
  maricopa_df = pd.read_csv('../preparedata/future_work/maricopa_future.csv')
  mesa_df = pd.read_csv('../preparedata/future_work/mesa_future.csv')
  phoenix_df = pd.read_csv('../preparedata/future_work/phoenix_future.csv')
  scott_df = pd.read_csv('../preparedata/future_work/scott_future.csv')
  tempe_df = pd.read_csv('../preparedata/future_work/tempe_future.csv')
  return [maricopa_df, mesa_df, phoenix_df, scott_df, tempe_df]

complete_df = pd.concat(retrieve_csv(), ignore_index=True)

In [0]:
# complete_df['reviews2013_sentiment_bin_score'] = complete_df['reviews2013_sentiment_bin_score'].astype('|S')
# complete_df['reviews2014_sentiment_bin_score'] = complete_df['reviews2014_sentiment_bin_score'].astype('|S')
# complete_df['reviews2015_sentiment_bin_score'] = complete_df['reviews2015_sentiment_bin_score'].astype('|S')

In [0]:
# complete_df = pd.read_csv('rate_sentiment_final.csv')

In [0]:
complete_df.head(3)

Unnamed: 0             business_id  ... competitiveness  peer_popularity
0           0  yGMCl0vYigshkXiZFIDTNw  ...        0.729167         0.039262
1           1  idF2DJg-WBk4eo2yY_7sHA  ...        0.896552         0.053687
2           2  221yaXPE1zmJqDvBVM__tw  ...        1.000000         0.008896

[3 rows x 33 columns]

In [0]:
new_completedf = complete_df.copy()
new_completedf = new_completedf.drop(['Unnamed: 0', 'business_id', 'name', 'review_count', 'is_open',
       'checkin_dates', 'reviews2013', 'reviews2014', 'reviews2015'
       ], axis = 1)

In [0]:
def computeNetScore(arr):
  arr = ast.literal_eval(arr)
  if(len(arr) is 0):
    return 0
  return np.sum(arr)/len(arr)

for i in range(len(new_completedf)):
    new_completedf['reviews2013_sentiment_bin_score'][i] = computeNetScore(new_completedf['reviews2013_sentiment_bin_score'][i])
    new_completedf['reviews2014_sentiment_bin_score'][i] = computeNetScore(new_completedf['reviews2014_sentiment_bin_score'][i])
    new_completedf['reviews2015_sentiment_bin_score'][i] = computeNetScore(new_completedf['reviews2015_sentiment_bin_score'][i])
    new_completedf['user_stars'][i] = computeNetScore(new_completedf['user_stars'][i])
    new_completedf['user_fans'][i] = computeNetScore(new_completedf['user_fans'][i])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.6/dis

In [0]:
%cd ..
# %ls

/content/drive/My Drive/COMP4641 Project


In [0]:
%cd /content/drive/My Drive/COMP4641 Project/race data/2013-2016 1yr/race/difference

/content/drive/My Drive/COMP4641 Project/race data/2013-2016 1yr/race/difference


In [0]:
dict_race = {'White':'White',
'Black or African American': 'American',
'American Indian and Alaska Native':'American',
# {'Cherokee tribal grouping': 'Cherokee'},
# {'Chippewa tribal grouping': 'Chippewa'},
# {'Navajo tribal grouping': 'Navajo'},
# {'Sioux tribal grouping': 'Sioux'},
# {'Asian': 'Asian'},
'Asian Indian': 'Indian',
'Chinese': 'Chinese',
'Filipino': 'Filipino',
'Japanese': 'Japanese',
'Korean': 'Korean',
'Vietnamese': 'Vietnamese',
'Other Asian': 'Asian',
'Native Hawaiian and Other Pacific Islander': 'Hawaiian',
'Native Hawaiian': 'Hawaiian'}
# {'Guamanian or Chamorro'},
# {'Samoan'},
# {'Other Pacific Islander'},
# {'Some other race'},
# {'White and Black or African American':'American'},
# {'White and American Indian and Alaska Native': 'Indian'},
# {'White and Asian': 'Asian'},
# {'Black or African American and American Indian and Alaska Native':}


In [0]:
# for index in range(len(new_completedf)):
new_completedf['race_2013_1'] = 0.0
new_completedf['race_2013_2'] = 0.0
new_completedf['race_2013_3'] = 0.0
new_completedf['race_2013_4'] = 0.0
new_completedf['race_2013_5'] = 0.0
new_completedf['race_2014_1'] = 0.0
new_completedf['race_2014_2'] = 0.0
new_completedf['race_2014_3'] = 0.0
new_completedf['race_2014_4'] = 0.0
new_completedf['race_2014_5'] = 0.0
new_completedf['race_2015_1'] = 0.0
new_completedf['race_2015_2'] = 0.0
new_completedf['race_2015_3'] = 0.0
new_completedf['race_2015_4'] = 0.0
new_completedf['race_2015_5'] = 0.0

def df_find(city):
  df_2013 = None
  df_2014 = None
  df_2015 = None
  if city == "Phoenix":
    df_2013 = pd.read_csv('difference_phoenix20131yr_race.csv')
    df_2014 = pd.read_csv('difference_phoenix20141yr_race.csv')
    df_2015 = pd.read_csv('difference_phoenix20151yr_race.csv')
  elif city == "Scottsdale":
    df_2013 = pd.read_csv('difference_scottsdale20131yr_race.csv')
    df_2014 = pd.read_csv('difference_scottsdale20141yr_race.csv')
    df_2015 = pd.read_csv('difference_scottsdale20151yr_race.csv')
  elif city == "Mesa":
    df_2013 = pd.read_csv('difference_mesa20131yr_race.csv')
    df_2014 = pd.read_csv('difference_mesa20141yr_race.csv')
    df_2015 = pd.read_csv('difference_mesa20151yr_race.csv')
  elif city == "Tempe":
    df_2013 = pd.read_csv('difference_tempe20131yr_race.csv')
    df_2014 = pd.read_csv('difference_tempe20141yr_race.csv')
    df_2015 = pd.read_csv('difference_tempe20151yr_race.csv')
  elif city == "Maricopa County":
    df_2013 = pd.read_csv('difference_maricopa20131yr_race.csv')
    df_2014 = pd.read_csv('difference_maricopa20141yr_race.csv')
    df_2015 = pd.read_csv('difference_maricopa20151yr_race.csv')
  
  return df_2013, df_2014, df_2015

for index in range(len(new_completedf)):
  df_2013 = None
  df_2014 = None
  df_2015 = None
  df_2013, df_2014, df_2015 = df_find(new_completedf['processed_city'][index])
  category = new_completedf['categories'][index]
  list_category = category.replace(' ', '').replace('&', ',').split(',')
  list_total = []
  for index_dict in range(len(dict_race)):
    list_total.append(0.0)
  for each_category in list_category:
    for index_dict in range(len(dict_race)):
      try:
        w1 = wordnet.synset(list(dict_race.values())[index_dict]+'.n.01') 
        w2 = wordnet.synset(each_category+'.n.01') 
        list_total[index_dict] += w1.wup_similarity(w2)
      except:
        continue
  # print(list_total)
  list_index = np.argsort(list_total)[-5:][::-1]
  top5_race = []
  for i in list_index:
    top5_race.append(list(dict_race.keys())[i])
  for i in range(len(df_2013)):
    for j in range(len(top5_race)):
      if (df_2013['race'][i] == top5_race[j]):
        new_completedf['race_2013_'+str(j+1)][index] = df_2013['difference'][i]
        new_completedf['race_2014_'+str(j+1)][index] = df_2014['difference'][i]
        new_completedf['race_2015_'+str(j+1)][index] = df_2015['difference'][i]



/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:71: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:72: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:73: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


In [0]:
new_completedf.head(20)

stars  ... race_2015_5
0     3.0  ...       -0.14
1     2.5  ...        0.02
2     2.5  ...       -0.14
3     2.0  ...        0.02
4     2.5  ...       -0.14
5     2.5  ...       -0.14
6     4.5  ...       -0.14
7     3.0  ...       -0.14
8     1.5  ...       -0.14
9     3.0  ...       -0.14
10    4.0  ...       -0.14
11    4.5  ...       -0.14
12    3.5  ...       -0.14
13    2.0  ...        0.02
14    4.0  ...       -0.14
15    3.5  ...       -0.14
16    1.5  ...        0.02
17    2.5  ...        0.06
18    4.5  ...       -0.14
19    2.5  ...        0.02

[20 rows x 39 columns]

In [0]:
# new_completedf.to_csv('race_feature_added_futurework.csv', header = True)
new_completedf = pd.read_csv('race_feature_added_futurework.csv')

In [0]:
complete_data = new_completedf.copy()

In [0]:
complete_data.head(3)

Unnamed: 0  stars  ... race_2015_4 race_2015_5
0           0    3.0  ...       -0.20       -0.14
1           1    2.5  ...        0.18        0.02
2           2    2.5  ...       -0.20       -0.14

[3 rows x 40 columns]

In [0]:
complete_data = complete_data.drop(['categories'], axis = 1)
complete_data = complete_data.drop(['Unnamed: 0'], axis = 1)
complete_data = complete_data.drop(['latitude'], axis = 1)
complete_data = complete_data.drop(['longitude'], axis = 1)
# complete_data = complete_data.drop(['processed_city'], axis = 1)
complete_data = complete_data.drop(['neighbours_same_cat_index'], axis = 1)
complete_data = complete_data.drop(['neighbour_index'], axis = 1)
complete_data = complete_data.drop(['neighbours_with_category'], axis = 1)
complete_data = complete_data.drop(['total_neighbour_checkins'], axis = 1)
complete_data = complete_data.drop(['neighbours_same_category'], axis = 1)

In [0]:
complete_data['rate_mid_2015'] = np.where(complete_data['rate_mid_2015'] > 0, 1, 0)

In [0]:
complete_data.head(7)

stars   processed_city  user_stars  ...  race_2015_3  race_2015_4  race_2015_5
0    3.0  Maricopa County    3.597136  ...         0.10        -0.20        -0.14
1    2.5  Maricopa County    3.447396  ...         0.06         0.18         0.02
2    2.5  Maricopa County    3.333077  ...         0.10        -0.20        -0.14
3    2.0  Maricopa County    3.286923  ...         0.06         0.18         0.02
4    2.5  Maricopa County    3.406204  ...         0.10        -0.20        -0.14
5    2.5  Maricopa County    3.205806  ...         0.10        -0.20        -0.14
6    4.5  Maricopa County    4.098333  ...         0.10        -0.20        -0.14

[7 rows x 31 columns]

In [0]:
complete_data.columns

Index(['stars', 'processed_city', 'user_stars', 'user_fans', 'rate_mid_2013',
       'rate_start_2014', 'rate_mid_2014', 'rate_start_2015', 'rate_mid_2015',
       'reviews2013_sentiment_bin_score', 'reviews2014_sentiment_bin_score',
       'reviews2015_sentiment_bin_score', 'num_neighbours', 'entropy',
       'competitiveness', 'peer_popularity', 'race_2013_1', 'race_2013_2',
       'race_2013_3', 'race_2013_4', 'race_2013_5', 'race_2014_1',
       'race_2014_2', 'race_2014_3', 'race_2014_4', 'race_2014_5',
       'race_2015_1', 'race_2015_2', 'race_2015_3', 'race_2015_4',
       'race_2015_5'],
      dtype='object')

In [0]:
complete_data['processed_city'].unique()

array(['Maricopa County', 'Mesa', 'Phoenix', 'Scottsdale', 'Tempe'],
      dtype=object)

In [0]:
phoenix_complete_data = complete_data[complete_data['processed_city'] == 'Phoenix'].reset_index().drop(['index'], axis = 1)
scottsdale_complete_data = complete_data[complete_data['processed_city'] == 'Scottsdale'].reset_index().drop(['index'], axis = 1)
mesa_complete_data = complete_data[complete_data['processed_city'] == 'Mesa'].reset_index().drop(['index'], axis = 1)
tempe_complete_data = complete_data[complete_data['processed_city'] == 'Tempe'].reset_index().drop(['index'], axis = 1)
maricopa_complete_data = complete_data[complete_data['processed_city'] == 'Maricopa County'].reset_index().drop(['index'], axis = 1)

In [0]:
phoenix_complete_data = phoenix_complete_data.drop(['processed_city'], axis = 1)
scottsdale_complete_data = scottsdale_complete_data.drop(['processed_city'], axis = 1)
mesa_complete_data = mesa_complete_data.drop(['processed_city'], axis = 1)
tempe_complete_data = tempe_complete_data.drop(['processed_city'], axis = 1)
maricopa_complete_data = maricopa_complete_data.drop(['processed_city'], axis = 1)
complete_data = complete_data.drop(['processed_city'], axis = 1)

In [0]:
phoenix_complete_data

stars  user_stars  user_fans  ...  race_2015_3  race_2015_4  race_2015_5
0       3.0    3.518421  12.894737  ...         0.00        -0.50        -0.04
1       3.5    3.630000   8.056140  ...        -0.12        -6.30         0.16
2       3.0    3.612143   2.714286  ...         0.00        -0.50        -0.04
3       3.5    3.632585  10.585034  ...         0.00        -0.50        -0.04
4       3.0    3.511667   2.666667  ...         0.00        -0.50        -0.04
...     ...         ...        ...  ...          ...          ...          ...
3705    2.5    3.319483   5.068966  ...         0.00        -0.50        -0.04
3706    2.0    3.000000   1.142857  ...         0.16         0.08        -0.08
3707    3.5    3.742500  13.000000  ...         0.00        -0.50        -0.04
3708    3.5    3.573846   6.307692  ...         0.00        -0.50        -0.04
3709    4.0    3.880000   8.181818  ...         0.00        -0.50        -0.04

[3710 rows x 30 columns]

In [0]:
from imblearn.over_sampling import RandomOverSampler
from sklearn.metrics import confusion_matrix

/usr/local/lib/python3.6/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)


# All Features

In [0]:
import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)

def all_data_split(all_lr):
  X_lrnn_data = all_lr.drop(['rate_mid_2015'], axis = 'columns').to_numpy()
  y_lrnn_data = all_lr['rate_mid_2015'].to_numpy()

  X_lrnn_data_processed = MinMaxScaler().fit_transform(X_lrnn_data)

  X_lrnn_train, X_lrnn_test, y_lrnn_train, y_lrnn_test = sklearn.model_selection.train_test_split(X_lrnn_data_processed, \
                                                                            y_lrnn_data, \
                                                                            test_size = 0.2) 
  oversample = RandomOverSampler(sampling_strategy='minority')                                                                  
  X_over, y_over = oversample.fit_resample(X_lrnn_train,y_lrnn_train)
  return X_over, X_lrnn_test, y_over, y_lrnn_test

X_lrnn_train, X_lrnn_test, y_lrnn_train, y_lrnn_test = all_data_split(complete_data.copy())
X_phoenix_train, X_phoenix_test, y_phoenix_train, y_phoenix_test = all_data_split(phoenix_complete_data.copy())
X_scottsdale_train, X_scottsdale_test, y_scottsdale_train, y_scottsdale_test = all_data_split(scottsdale_complete_data.copy())
X_mesa_train, X_mesa_test, y_mesa_train, y_mesa_test = all_data_split(mesa_complete_data.copy())
X_tempe_train, X_tempe_test, y_tempe_train, y_tempe_test = all_data_split(tempe_complete_data.copy())
X_maricopa_train, X_maricopa_test, y_maricopa_train, y_maricopa_test = all_data_split(maricopa_complete_data.copy())

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarni

In [0]:
def train_test_model(X_lrnn_train, y_lrnn_train, X_lrnn_test, y_lrnn_test, model_type):
  feature_logistic_accuracy = 0
  feature_logistic_F1_score = 0
  for i in range(len(lr)):
    feature_logistic = linear_model.SGDClassifier(loss = 'log', penalty = 'elasticnet', learning_rate = 'constant', eta0 = 0.01, verbose=0)
    feature_logistic.fit(X_lrnn_train, y_lrnn_train)
    feature_logistic_prediction = feature_logistic.predict(X_lrnn_test)
    # print(feature_logistic_prediction)
    # print(y_lrnn_test)
    feature_logistic_accuracy = sklearn.metrics.accuracy_score(y_lrnn_test, feature_logistic_prediction)
    feature_logistic_F1_score = sklearn.metrics.f1_score(y_lrnn_test, feature_logistic_prediction)
  print(confusion_matrix(y_lrnn_test, feature_logistic_prediction))
  print(model_type, "Accuracy:", feature_logistic_accuracy)
  print(model_type, "F1:", feature_logistic_F1_score)
print("All")
train_test_model(X_lrnn_train, y_lrnn_train, X_lrnn_test, y_lrnn_test, "Overall")
train_test_model(X_phoenix_train, y_phoenix_train, X_phoenix_test, y_phoenix_test, "Phoenix")
train_test_model(X_scottsdale_train, y_scottsdale_train, X_scottsdale_test, y_scottsdale_test, "Scottsdale")
train_test_model(X_mesa_train, y_mesa_train, X_mesa_test, y_mesa_test, "Mesa")
train_test_model(X_tempe_train, y_tempe_train, X_tempe_test, y_tempe_test, "Tempe")
train_test_model(X_maricopa_train, y_maricopa_train, X_maricopa_test, y_maricopa_test, "Maricopa")

All
[[912 205]
 [323 157]]
Overall Accuracy: 0.6693800876643707
Overall F1: 0.37292161520190026
[[343 168]
 [118 113]]
Phoenix Accuracy: 0.6145552560646901
Phoenix F1: 0.44140625
[[93 83]
 [23 40]]
Scottsdale Accuracy: 0.5564853556485355
Scottsdale F1: 0.43010752688172044
[[137  10]
 [ 65   0]]
Mesa Accuracy: 0.6462264150943396
Mesa F1: 0.0
[[49 81]
 [13 37]]
Tempe Accuracy: 0.4777777777777778
Tempe F1: 0.44047619047619047
[[104  46]
 [ 42  34]]
Maricopa Accuracy: 0.6106194690265486
Maricopa F1: 0.4358974358974359


## Removing stars

In [0]:
# import sys
# import numpy
# numpy.set_printoptions(threshold=sys.maxsize)

# def star_data_split(stars_lr):
#   X_lrnn_data = stars_lr.drop(['stars', 'user_stars', 'user_fans', 'rate_mid_2015'], axis = 'columns').to_numpy()
#   y_lrnn_data = stars_lr['rate_mid_2015'].to_numpy()

#   X_lrnn_data_processed = MinMaxScaler().fit_transform(X_lrnn_data)

#   X_lrnn_train, X_lrnn_test, y_lrnn_train, y_lrnn_test = sklearn.model_selection.train_test_split(X_lrnn_data_processed, \
#                                                                             y_lrnn_data, \
#                                                                             test_size = 0.2) 
#   return X_lrnn_train, X_lrnn_test, y_lrnn_train, y_lrnn_test

# X_lrnn_train, X_lrnn_test, y_lrnn_train, y_lrnn_test = star_data_split(complete_data.copy())
# X_phoenix_train, X_phoenix_test, y_phoenix_train, y_phoenix_test = star_data_split(phoenix_complete_data.copy())
# X_scottsdale_train, X_scottsdale_test, y_scottsdale_train, y_scottsdale_test = star_data_split(scottsdale_complete_data.copy())
# X_mesa_train, X_mesa_test, y_mesa_train, y_mesa_test = star_data_split(mesa_complete_data.copy())
# X_tempe_train, X_tempe_test, y_tempe_train, y_tempe_test = star_data_split(tempe_complete_data.copy())
# X_maricopa_train, X_maricopa_test, y_maricopa_train, y_maricopa_test = star_data_split(maricopa_complete_data.copy())


In [0]:
import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)

def star_data_split(stars_lr):
  X_lrnn_data = stars_lr.drop(['stars', 'user_stars', 'user_fans', 'rate_mid_2015'], axis = 'columns').to_numpy()
  y_lrnn_data = stars_lr['rate_mid_2015'].to_numpy()

  X_lrnn_data_processed = MinMaxScaler().fit_transform(X_lrnn_data)

  X_lrnn_train, X_lrnn_test, y_lrnn_train, y_lrnn_test = sklearn.model_selection.train_test_split(X_lrnn_data_processed, \
                                                                            y_lrnn_data, \
                                                                            test_size = 0.2) 
  oversample = RandomOverSampler(sampling_strategy='minority')                                                                  
  X_over, y_over = oversample.fit_resample(X_lrnn_train,y_lrnn_train)
  return X_over, X_lrnn_test, y_over, y_lrnn_test

X_lrnn_train, X_lrnn_test, y_lrnn_train, y_lrnn_test = star_data_split(complete_data.copy())
X_phoenix_train, X_phoenix_test, y_phoenix_train, y_phoenix_test = star_data_split(phoenix_complete_data.copy())
X_scottsdale_train, X_scottsdale_test, y_scottsdale_train, y_scottsdale_test = star_data_split(scottsdale_complete_data.copy())
X_mesa_train, X_mesa_test, y_mesa_train, y_mesa_test = star_data_split(mesa_complete_data.copy())
X_tempe_train, X_tempe_test, y_tempe_train, y_tempe_test = star_data_split(tempe_complete_data.copy())
X_maricopa_train, X_maricopa_test, y_maricopa_train, y_maricopa_test = star_data_split(maricopa_complete_data.copy())


/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarni

In [0]:
X = X_scottsdale_train.copy()
y = y_scottsdale_train.copy()
len(X_phoenix_train), len(X_scottsdale_train), len(X_mesa_train), len(X_tempe_train), len(X_maricopa_train)

(4052, 1386, 1186, 1024, 1170)

In [0]:
cd = complete_data.copy()

In [0]:
X_x = cd.drop(['stars', 'user_stars', 'user_fans', 'rate_mid_2015'], axis = 'columns').to_numpy()
Y_y = cd['rate_mid_2015'].to_numpy()

X_p = MinMaxScaler().fit_transform(X_x)

X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(X_p, \
                                                                            Y_y, \
                                                                            test_size = 0.2) 
oversample = RandomOverSampler(sampling_strategy='minority')
X_over, y_over = oversample.fit_resample(X_train,y_train)


/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


In [0]:
len(X_over)

8798

In [0]:

def train_test_model(X_lrnn_train, y_lrnn_train, X_lrnn_test, y_lrnn_test, model_type):
  lr = [1]
  feature_logistic_accuracy = 0
  feature_logistic_F1_score = 0
  for i in range(len(lr)):
    feature_logistic = linear_model.SGDClassifier(loss = 'log', penalty = 'l1', learning_rate = 'adaptive', eta0 = lr[i], verbose=0)
    feature_logistic.fit(X_lrnn_train, y_lrnn_train)
    feature_logistic_prediction = feature_logistic.predict(X_lrnn_test)
    # print(feature_logistic_prediction)
    # print(y_lrnn_test)
    feature_logistic_accuracy = sklearn.metrics.accuracy_score(y_lrnn_test, feature_logistic_prediction)
    feature_logistic_F1_score = sklearn.metrics.f1_score(y_lrnn_test, feature_logistic_prediction)
  print(confusion_matrix(y_lrnn_test, feature_logistic_prediction))
  print(model_type, "Accuracy:", feature_logistic_accuracy)
  print(model_type, "F1:", feature_logistic_F1_score)
print("-Stars")
train_test_model(X_lrnn_train, y_lrnn_train, X_lrnn_test, y_lrnn_test, "Overall")
train_test_model(X_phoenix_train, y_phoenix_train, X_phoenix_test, y_phoenix_test, "Phoenix")
train_test_model(X_scottsdale_train, y_scottsdale_train, X_scottsdale_test, y_scottsdale_test, "Scottsdale")
train_test_model(X_mesa_train, y_mesa_train, X_mesa_test, y_mesa_test, "Mesa")
train_test_model(X_tempe_train, y_tempe_train, X_tempe_test, y_tempe_test, "Tempe")
train_test_model(X_maricopa_train, y_maricopa_train, X_maricopa_test, y_maricopa_test, "Maricopa")


-Stars
[[641 439]
 [236 281]]
Overall Accuracy: 0.5773324984345648
Overall F1: 0.45432497978981407
[[301 218]
 [ 95 128]]
Phoenix Accuracy: 0.578167115902965
Phoenix F1: 0.44991212653778556
[[98 66]
 [31 44]]
Scottsdale Accuracy: 0.5941422594142259
Scottsdale F1: 0.4756756756756757
[[84 61]
 [29 38]]
Mesa Accuracy: 0.5754716981132075
Mesa F1: 0.45783132530120485
[[76 48]
 [19 37]]
Tempe Accuracy: 0.6277777777777778
Tempe F1: 0.5248226950354609
[[85 65]
 [36 40]]
Maricopa Accuracy: 0.5530973451327433
Maricopa F1: 0.4419889502762431


##Removing rates

In [0]:

# def rate_data_split(rate_lr):
#   X_lrnn_data = rate_lr.drop(['rate_mid_2013', 'rate_start_2014',
#        'rate_mid_2014', 'rate_start_2015', 'rate_mid_2015'], axis = 'columns').to_numpy()
#   y_lrnn_data = rate_lr['rate_mid_2015'].to_numpy()

#   X_lrnn_data_processed = MinMaxScaler().fit_transform(X_lrnn_data)

#   X_lrnn_train, X_lrnn_test, y_lrnn_train, y_lrnn_test = sklearn.model_selection.train_test_split(X_lrnn_data_processed, \
#                                                                             y_lrnn_data, \
#                                                                             test_size = 0.2) 
#   return X_lrnn_train, X_lrnn_test, y_lrnn_train, y_lrnn_test

# X_lrnn_train, X_lrnn_test, y_lrnn_train, y_lrnn_test = rate_data_split(complete_data.copy())
# X_phoenix_train, X_phoenix_test, y_phoenix_train, y_phoenix_test = rate_data_split(phoenix_complete_data.copy())
# X_scottsdale_train, X_scottsdale_test, y_scottsdale_train, y_scottsdale_test = rate_data_split(scottsdale_complete_data.copy())
# X_mesa_train, X_mesa_test, y_mesa_train, y_mesa_test = rate_data_split(mesa_complete_data.copy())
# X_tempe_train, X_tempe_test, y_tempe_train, y_tempe_test = rate_data_split(tempe_complete_data.copy())
# X_maricopa_train, X_maricopa_test, y_maricopa_train, y_maricopa_test = rate_data_split(maricopa_complete_data.copy())

In [0]:
def rate_data_split(rate_lr):
  X_lrnn_data = rate_lr.drop(['rate_mid_2013', 'rate_start_2014',
       'rate_mid_2014', 'rate_start_2015', 'rate_mid_2015'], axis = 'columns').to_numpy()
  y_lrnn_data = rate_lr['rate_mid_2015'].to_numpy()

  X_lrnn_data_processed = MinMaxScaler().fit_transform(X_lrnn_data)

  X_lrnn_train, X_lrnn_test, y_lrnn_train, y_lrnn_test = sklearn.model_selection.train_test_split(X_lrnn_data_processed, \
                                                                            y_lrnn_data, \
                                                                            test_size = 0.2) 
  oversample = RandomOverSampler(sampling_strategy='minority')                                                                  
  X_over, y_over = oversample.fit_resample(X_lrnn_train,y_lrnn_train)
  return X_over, X_lrnn_test, y_over, y_lrnn_test

X_lrnn_train, X_lrnn_test, y_lrnn_train, y_lrnn_test = rate_data_split(complete_data.copy())
X_phoenix_train, X_phoenix_test, y_phoenix_train, y_phoenix_test = rate_data_split(phoenix_complete_data.copy())
X_scottsdale_train, X_scottsdale_test, y_scottsdale_train, y_scottsdale_test = rate_data_split(scottsdale_complete_data.copy())
X_mesa_train, X_mesa_test, y_mesa_train, y_mesa_test = rate_data_split(mesa_complete_data.copy())
X_tempe_train, X_tempe_test, y_tempe_train, y_tempe_test = rate_data_split(tempe_complete_data.copy())
X_maricopa_train, X_maricopa_test, y_maricopa_train, y_maricopa_test = rate_data_split(maricopa_complete_data.copy())

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarni

In [0]:

def train_test_model(X_lrnn_train, y_lrnn_train, X_lrnn_test, y_lrnn_test, model_type):
  lr = [1.0]
  feature_logistic_accuracy = 0
  feature_logistic_F1_score = 0
  for i in range(len(lr)):
    feature_logistic = linear_model.SGDClassifier(loss = 'log', penalty = 'l1', learning_rate = 'adaptive', eta0 = lr[i], verbose=0)
    feature_logistic.fit(X_lrnn_train, y_lrnn_train)
    feature_logistic_prediction = feature_logistic.predict(X_lrnn_test)
    # print(feature_logistic_prediction)
    # print(y_lrnn_test)
    feature_logistic_accuracy = sklearn.metrics.accuracy_score(y_lrnn_test, feature_logistic_prediction)
    feature_logistic_F1_score = sklearn.metrics.f1_score(y_lrnn_test, feature_logistic_prediction)
  
  print(confusion_matrix(y_lrnn_test, feature_logistic_prediction))
  print(model_type, "Accuracy:", feature_logistic_accuracy)
  print(model_type, "F1:", feature_logistic_F1_score)  
  

print("-Rates")
train_test_model(X_lrnn_train, y_lrnn_train, X_lrnn_test, y_lrnn_test, "Overall")
train_test_model(X_phoenix_train, y_phoenix_train, X_phoenix_test, y_phoenix_test, "Phoenix")
train_test_model(X_scottsdale_train, y_scottsdale_train, X_scottsdale_test, y_scottsdale_test, "Scottsdale")
train_test_model(X_mesa_train, y_mesa_train, X_mesa_test, y_mesa_test, "Mesa")
train_test_model(X_tempe_train, y_tempe_train, X_tempe_test, y_tempe_test, "Tempe")
train_test_model(X_maricopa_train, y_maricopa_train, X_maricopa_test, y_maricopa_test, "Maricopa")


-Rates
[[686 419]
 [218 274]]
Overall Accuracy: 0.6011271133375078
Overall F1: 0.46244725738396625
[[293 217]
 [105 127]]
Phoenix Accuracy: 0.5660377358490566
Phoenix F1: 0.4409722222222222
[[101  77]
 [ 29  32]]
Scottsdale Accuracy: 0.5564853556485355
Scottsdale F1: 0.37647058823529417
[[74 66]
 [40 32]]
Mesa Accuracy: 0.5
Mesa F1: 0.3764705882352941
[[79 45]
 [24 32]]
Tempe Accuracy: 0.6166666666666667
Tempe F1: 0.481203007518797
[[88 51]
 [47 40]]
Maricopa Accuracy: 0.5663716814159292
Maricopa F1: 0.449438202247191


##Removing sentiment

In [0]:
def rate_data_split(sentiment_lr):

  X_lrnn_data = sentiment_lr.drop(['reviews2013_sentiment_bin_score', 'reviews2014_sentiment_bin_score',
       'reviews2015_sentiment_bin_score', 'rate_mid_2015'], axis = 'columns').to_numpy()
  y_lrnn_data = sentiment_lr['rate_mid_2015'].to_numpy()

  X_lrnn_data_processed = MinMaxScaler().fit_transform(X_lrnn_data)

  X_lrnn_train, X_lrnn_test, y_lrnn_train, y_lrnn_test = sklearn.model_selection.train_test_split(X_lrnn_data_processed, \
                                                                            y_lrnn_data, \
                                                                            test_size = 0.2) 
  oversample = RandomOverSampler(sampling_strategy='minority')                                                                  
  X_over, y_over = oversample.fit_resample(X_lrnn_train,y_lrnn_train)
  return X_over, X_lrnn_test, y_over, y_lrnn_test


X_lrnn_train, X_lrnn_test, y_lrnn_train, y_lrnn_test = rate_data_split(complete_data.copy())
X_phoenix_train, X_phoenix_test, y_phoenix_train, y_phoenix_test = rate_data_split(phoenix_complete_data.copy())
X_scottsdale_train, X_scottsdale_test, y_scottsdale_train, y_scottsdale_test = rate_data_split(scottsdale_complete_data.copy())
X_mesa_train, X_mesa_test, y_mesa_train, y_mesa_test = rate_data_split(mesa_complete_data.copy())
X_tempe_train, X_tempe_test, y_tempe_train, y_tempe_test = rate_data_split(tempe_complete_data.copy())
X_maricopa_train, X_maricopa_test, y_maricopa_train, y_maricopa_test = rate_data_split(maricopa_complete_data.copy())

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarni

In [0]:

def train_test_model(X_lrnn_train, y_lrnn_train, X_lrnn_test, y_lrnn_test, model_type):
  lr = [1.0]
  feature_logistic_accuracy = 0
  feature_logistic_F1_score = 0
  for i in range(len(lr)):
    feature_logistic = linear_model.SGDClassifier(loss = 'log', penalty = 'l1', learning_rate = 'adaptive', eta0 = lr[i], verbose=0)
    feature_logistic.fit(X_lrnn_train, y_lrnn_train)
    feature_logistic_prediction = feature_logistic.predict(X_lrnn_test)
    # print(feature_logistic_prediction)
    # print(y_lrnn_test)
    feature_logistic_accuracy = sklearn.metrics.accuracy_score(y_lrnn_test, feature_logistic_prediction)
    feature_logistic_F1_score = sklearn.metrics.f1_score(y_lrnn_test, feature_logistic_prediction)
    
  print(confusion_matrix(y_lrnn_test, feature_logistic_prediction))
  print(model_type, "Accuracy:", feature_logistic_accuracy)
  print(model_type, "F1:", feature_logistic_F1_score)

print("-Sentiment") 
train_test_model(X_lrnn_train, y_lrnn_train, X_lrnn_test, y_lrnn_test, "Overall")
train_test_model(X_phoenix_train, y_phoenix_train, X_phoenix_test, y_phoenix_test, "Phoenix")
train_test_model(X_scottsdale_train, y_scottsdale_train, X_scottsdale_test, y_scottsdale_test, "Scottsdale")
train_test_model(X_mesa_train, y_mesa_train, X_mesa_test, y_mesa_test, "Mesa")
train_test_model(X_tempe_train, y_tempe_train, X_tempe_test, y_tempe_test, "Tempe")
train_test_model(X_maricopa_train, y_maricopa_train, X_maricopa_test, y_maricopa_test, "Maricopa")


-Sentiment
[[526 561]
 [174 336]]
Overall Accuracy: 0.5397620538509705
Overall F1: 0.47761194029850734
[[216 279]
 [ 86 161]]
Phoenix Accuracy: 0.5080862533692723
Phoenix F1: 0.4687045123726346
[[93 90]
 [28 28]]
Scottsdale Accuracy: 0.5062761506276151
Scottsdale F1: 0.3218390804597701
[[83 69]
 [30 30]]
Mesa Accuracy: 0.5330188679245284
Mesa F1: 0.37735849056603776
[[68 67]
 [23 22]]
Tempe Accuracy: 0.5
Tempe F1: 0.3283582089552239
[[83 63]
 [24 56]]
Maricopa Accuracy: 0.6150442477876106
Maricopa F1: 0.5628140703517589


##Removing Race

In [0]:

def rate_data_split(race_lr):
  X_lrnn_data = race_lr.drop(['race_2013_1', 'race_2013_2',
       'race_2013_3', 'race_2013_4', 'race_2013_5', 'race_2014_1',
       'race_2014_2', 'race_2014_3', 'race_2014_4', 'race_2014_5',
       'race_2015_1', 'race_2015_2', 'race_2015_3', 'race_2015_4',
       'race_2015_5', 'rate_mid_2015'], axis = 'columns').to_numpy()
  y_lrnn_data = race_lr['rate_mid_2015'].to_numpy()

  X_lrnn_data_processed = MinMaxScaler().fit_transform(X_lrnn_data)

  X_lrnn_train, X_lrnn_test, y_lrnn_train, y_lrnn_test = sklearn.model_selection.train_test_split(X_lrnn_data_processed, \
                                                                            y_lrnn_data, \
                                                                            test_size = 0.2) 
  oversample = RandomOverSampler(sampling_strategy='minority')                                                                  
  X_over, y_over = oversample.fit_resample(X_lrnn_train,y_lrnn_train)
  return X_over, X_lrnn_test, y_over, y_lrnn_test
  

X_lrnn_train, X_lrnn_test, y_lrnn_train, y_lrnn_test = rate_data_split(complete_data.copy())
X_phoenix_train, X_phoenix_test, y_phoenix_train, y_phoenix_test = rate_data_split(phoenix_complete_data.copy())
X_scottsdale_train, X_scottsdale_test, y_scottsdale_train, y_scottsdale_test = rate_data_split(scottsdale_complete_data.copy())
X_mesa_train, X_mesa_test, y_mesa_train, y_mesa_test = rate_data_split(mesa_complete_data.copy())
X_tempe_train, X_tempe_test, y_tempe_train, y_tempe_test = rate_data_split(tempe_complete_data.copy())
X_maricopa_train, X_maricopa_test, y_maricopa_train, y_maricopa_test = rate_data_split(maricopa_complete_data.copy())

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarni

In [0]:

def train_test_model(X_lrnn_train, y_lrnn_train, X_lrnn_test, y_lrnn_test, model_type):
  lr = [1.0]
  feature_logistic_accuracy = 0
  feature_logistic_F1_score = 0
  for i in range(len(lr)):
    feature_logistic = linear_model.SGDClassifier(loss = 'log', penalty = 'l1', learning_rate = 'adaptive', eta0 = lr[i], verbose=0)
    feature_logistic.fit(X_lrnn_train, y_lrnn_train)
    feature_logistic_prediction = feature_logistic.predict(X_lrnn_test)
    # print(feature_logistic_prediction)
    # print(y_lrnn_test)
    feature_logistic_accuracy = sklearn.metrics.accuracy_score(y_lrnn_test, feature_logistic_prediction)
    feature_logistic_F1_score = sklearn.metrics.f1_score(y_lrnn_test, feature_logistic_prediction)
    
  print(confusion_matrix(y_lrnn_test, feature_logistic_prediction))
  print(model_type, "Accuracy:", feature_logistic_accuracy)
  print(model_type, "F1:", feature_logistic_F1_score)

print("-Race")
train_test_model(X_lrnn_train, y_lrnn_train, X_lrnn_test, y_lrnn_test, "Overall")
train_test_model(X_phoenix_train, y_phoenix_train, X_phoenix_test, y_phoenix_test, "Phoenix")
train_test_model(X_scottsdale_train, y_scottsdale_train, X_scottsdale_test, y_scottsdale_test, "Scottsdale")
train_test_model(X_mesa_train, y_mesa_train, X_mesa_test, y_mesa_test, "Mesa")
train_test_model(X_tempe_train, y_tempe_train, X_tempe_test, y_tempe_test, "Tempe")
train_test_model(X_maricopa_train, y_maricopa_train, X_maricopa_test, y_maricopa_test, "Maricopa")


-Race
[[633 467]
 [212 285]]
Overall Accuracy: 0.5748278021289919
Overall F1: 0.45636509207365894
[[296 234]
 [ 90 122]]
Phoenix Accuracy: 0.5633423180592992
Phoenix F1: 0.4295774647887324
[[114  67]
 [ 20  38]]
Scottsdale Accuracy: 0.6359832635983264
Scottsdale F1: 0.46625766871165636
[[83 64]
 [26 39]]
Mesa Accuracy: 0.5754716981132075
Mesa F1: 0.4642857142857143
[[78 52]
 [23 27]]
Tempe Accuracy: 0.5833333333333334
Tempe F1: 0.41860465116279066
[[96 62]
 [30 38]]
Maricopa Accuracy: 0.5929203539823009
Maricopa F1: 0.4523809523809524


##Removing Density

In [0]:
#'num_neighbours', 'entropy', 'competitiveness', 'peer_popularity'
def rate_data_split(density_lr):
  X_lrnn_data = density_lr.drop(['num_neighbours', 'rate_mid_2015'], axis = 'columns').to_numpy()
  y_lrnn_data = density_lr['rate_mid_2015'].to_numpy()

  X_lrnn_data_processed = MinMaxScaler().fit_transform(X_lrnn_data)

  X_lrnn_train, X_lrnn_test, y_lrnn_train, y_lrnn_test = sklearn.model_selection.train_test_split(X_lrnn_data_processed, \
                                                                            y_lrnn_data, \
                                                                            test_size = 0.2) 
  oversample = RandomOverSampler(sampling_strategy='minority')                                                                  
  X_over, y_over = oversample.fit_resample(X_lrnn_train,y_lrnn_train)
  return X_over, X_lrnn_test, y_over, y_lrnn_test
  

X_lrnn_train, X_lrnn_test, y_lrnn_train, y_lrnn_test = rate_data_split(complete_data.copy())
X_phoenix_train, X_phoenix_test, y_phoenix_train, y_phoenix_test = rate_data_split(phoenix_complete_data.copy())
X_scottsdale_train, X_scottsdale_test, y_scottsdale_train, y_scottsdale_test = rate_data_split(scottsdale_complete_data.copy())
X_mesa_train, X_mesa_test, y_mesa_train, y_mesa_test = rate_data_split(mesa_complete_data.copy())
X_tempe_train, X_tempe_test, y_tempe_train, y_tempe_test = rate_data_split(tempe_complete_data.copy())
X_maricopa_train, X_maricopa_test, y_maricopa_train, y_maricopa_test = rate_data_split(maricopa_complete_data.copy())

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarni

In [0]:

def train_test_model(X_lrnn_train, y_lrnn_train, X_lrnn_test, y_lrnn_test, model_type):
  lr = [1.0]
  feature_logistic_accuracy = 0
  feature_logistic_F1_score = 0
  for i in range(len(lr)):
    feature_logistic = linear_model.SGDClassifier(loss = 'log', penalty = 'l1', learning_rate = 'adaptive', eta0 = lr[i], verbose=0)
    feature_logistic.fit(X_lrnn_train, y_lrnn_train)
    feature_logistic_prediction = feature_logistic.predict(X_lrnn_test)
    # print(feature_logistic_prediction)
    # print(y_lrnn_test)
    feature_logistic_accuracy = sklearn.metrics.accuracy_score(y_lrnn_test, feature_logistic_prediction)
    feature_logistic_F1_score = sklearn.metrics.f1_score(y_lrnn_test, feature_logistic_prediction)
    
  print(confusion_matrix(y_lrnn_test, feature_logistic_prediction))
  print(model_type, "Accuracy:", feature_logistic_accuracy)
  print(model_type, "F1:", feature_logistic_F1_score)

print("-Density")
train_test_model(X_lrnn_train, y_lrnn_train, X_lrnn_test, y_lrnn_test, "Overall")
train_test_model(X_phoenix_train, y_phoenix_train, X_phoenix_test, y_phoenix_test, "Phoenix")
train_test_model(X_scottsdale_train, y_scottsdale_train, X_scottsdale_test, y_scottsdale_test, "Scottsdale")
train_test_model(X_mesa_train, y_mesa_train, X_mesa_test, y_mesa_test, "Mesa")
train_test_model(X_tempe_train, y_tempe_train, X_tempe_test, y_tempe_test, "Tempe")
train_test_model(X_maricopa_train, y_maricopa_train, X_maricopa_test, y_maricopa_test, "Maricopa")


-Race
[[678 428]
 [229 262]]
Overall Accuracy: 0.588603631809643
Overall F1: 0.44369178662150727
[[300 211]
 [103 128]]
Phoenix Accuracy: 0.5768194070080862
Phoenix F1: 0.4491228070175438
[[103  74]
 [ 25  37]]
Scottsdale Accuracy: 0.5857740585774058
Scottsdale F1: 0.42774566473988435
[[101  60]
 [ 15  36]]
Mesa Accuracy: 0.6462264150943396
Mesa F1: 0.48979591836734687
[[77 53]
 [17 33]]
Tempe Accuracy: 0.6111111111111112
Tempe F1: 0.4852941176470589
[[84 60]
 [43 39]]
Maricopa Accuracy: 0.5442477876106194
Maricopa F1: 0.430939226519337


##Removing Entropy

In [0]:
#'num_neighbours', 'entropy', 'competitiveness', 'peer_popularity'
def rate_data_split(entropy_lr):
  X_lrnn_data = entropy_lr.drop(['entropy', 'rate_mid_2015'], axis = 'columns').to_numpy()
  y_lrnn_data = entropy_lr['rate_mid_2015'].to_numpy()

  X_lrnn_data_processed = MinMaxScaler().fit_transform(X_lrnn_data)

  X_lrnn_train, X_lrnn_test, y_lrnn_train, y_lrnn_test = sklearn.model_selection.train_test_split(X_lrnn_data_processed, \
                                                                            y_lrnn_data, \
                                                                            test_size = 0.2) 
  oversample = RandomOverSampler(sampling_strategy='minority')                                                                  
  X_over, y_over = oversample.fit_resample(X_lrnn_train,y_lrnn_train)
  return X_over, X_lrnn_test, y_over, y_lrnn_test
  

X_lrnn_train, X_lrnn_test, y_lrnn_train, y_lrnn_test = rate_data_split(complete_data.copy())
X_phoenix_train, X_phoenix_test, y_phoenix_train, y_phoenix_test = rate_data_split(phoenix_complete_data.copy())
X_scottsdale_train, X_scottsdale_test, y_scottsdale_train, y_scottsdale_test = rate_data_split(scottsdale_complete_data.copy())
X_mesa_train, X_mesa_test, y_mesa_train, y_mesa_test = rate_data_split(mesa_complete_data.copy())
X_tempe_train, X_tempe_test, y_tempe_train, y_tempe_test = rate_data_split(tempe_complete_data.copy())
X_maricopa_train, X_maricopa_test, y_maricopa_train, y_maricopa_test = rate_data_split(maricopa_complete_data.copy())

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarni

In [0]:

def train_test_model(X_lrnn_train, y_lrnn_train, X_lrnn_test, y_lrnn_test, model_type):
  lr = [1.0]
  feature_logistic_accuracy = 0
  feature_logistic_F1_score = 0
  for i in range(len(lr)):
    feature_logistic = linear_model.SGDClassifier(loss = 'log', penalty = 'l1', learning_rate = 'adaptive', eta0 = lr[i], verbose=0)
    feature_logistic.fit(X_lrnn_train, y_lrnn_train)
    feature_logistic_prediction = feature_logistic.predict(X_lrnn_test)
    # print(feature_logistic_prediction)
    # print(y_lrnn_test)
    feature_logistic_accuracy = sklearn.metrics.accuracy_score(y_lrnn_test, feature_logistic_prediction)
    feature_logistic_F1_score = sklearn.metrics.f1_score(y_lrnn_test, feature_logistic_prediction)
    
  print(confusion_matrix(y_lrnn_test, feature_logistic_prediction))
  print(model_type, "Accuracy:", feature_logistic_accuracy)
  print(model_type, "F1:", feature_logistic_F1_score)

print("-Entropy")
train_test_model(X_lrnn_train, y_lrnn_train, X_lrnn_test, y_lrnn_test, "Overall")
train_test_model(X_phoenix_train, y_phoenix_train, X_phoenix_test, y_phoenix_test, "Phoenix")
train_test_model(X_scottsdale_train, y_scottsdale_train, X_scottsdale_test, y_scottsdale_test, "Scottsdale")
train_test_model(X_mesa_train, y_mesa_train, X_mesa_test, y_mesa_test, "Mesa")
train_test_model(X_tempe_train, y_tempe_train, X_tempe_test, y_tempe_test, "Tempe")
train_test_model(X_maricopa_train, y_maricopa_train, X_maricopa_test, y_maricopa_test, "Maricopa")


-Race
[[650 445]
 [220 282]]
Overall Accuracy: 0.5835942391984972
Overall F1: 0.45890968266883647
[[318 209]
 [ 91 124]]
Phoenix Accuracy: 0.5956873315363881
Phoenix F1: 0.45255474452554745
[[106  68]
 [ 26  39]]
Scottsdale Accuracy: 0.606694560669456
Scottsdale F1: 0.45348837209302323
[[84 59]
 [27 42]]
Mesa Accuracy: 0.5943396226415094
Mesa F1: 0.49411764705882355
[[66 58]
 [19 37]]
Tempe Accuracy: 0.5722222222222222
Tempe F1: 0.49006622516556286
[[83 67]
 [30 46]]
Maricopa Accuracy: 0.5707964601769911
Maricopa F1: 0.48677248677248675


##Removing Competitiveness

In [0]:
#'num_neighbours', 'entropy', 'competitiveness', 'peer_popularity'
def rate_data_split(competitiveness_lr):
  X_lrnn_data = competitiveness_lr.drop(['competitiveness', 'rate_mid_2015'], axis = 'columns').to_numpy()
  y_lrnn_data = competitiveness_lr['rate_mid_2015'].to_numpy()

  X_lrnn_data_processed = MinMaxScaler().fit_transform(X_lrnn_data)

  X_lrnn_train, X_lrnn_test, y_lrnn_train, y_lrnn_test = sklearn.model_selection.train_test_split(X_lrnn_data_processed, \
                                                                            y_lrnn_data, \
                                                                            test_size = 0.2) 
  oversample = RandomOverSampler(sampling_strategy='minority')                                                                  
  X_over, y_over = oversample.fit_resample(X_lrnn_train,y_lrnn_train)
  return X_over, X_lrnn_test, y_over, y_lrnn_test
  

X_lrnn_train, X_lrnn_test, y_lrnn_train, y_lrnn_test = rate_data_split(complete_data.copy())
X_phoenix_train, X_phoenix_test, y_phoenix_train, y_phoenix_test = rate_data_split(phoenix_complete_data.copy())
X_scottsdale_train, X_scottsdale_test, y_scottsdale_train, y_scottsdale_test = rate_data_split(scottsdale_complete_data.copy())
X_mesa_train, X_mesa_test, y_mesa_train, y_mesa_test = rate_data_split(mesa_complete_data.copy())
X_tempe_train, X_tempe_test, y_tempe_train, y_tempe_test = rate_data_split(tempe_complete_data.copy())
X_maricopa_train, X_maricopa_test, y_maricopa_train, y_maricopa_test = rate_data_split(maricopa_complete_data.copy())

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarni

In [0]:

def train_test_model(X_lrnn_train, y_lrnn_train, X_lrnn_test, y_lrnn_test, model_type):
  lr = [1.0]
  feature_logistic_accuracy = 0
  feature_logistic_F1_score = 0
  for i in range(len(lr)):
    feature_logistic = linear_model.SGDClassifier(loss = 'log', penalty = 'l1', learning_rate = 'adaptive', eta0 = lr[i], verbose=0)
    feature_logistic.fit(X_lrnn_train, y_lrnn_train)
    feature_logistic_prediction = feature_logistic.predict(X_lrnn_test)
    # print(feature_logistic_prediction)
    # print(y_lrnn_test)
    feature_logistic_accuracy = sklearn.metrics.accuracy_score(y_lrnn_test, feature_logistic_prediction)
    feature_logistic_F1_score = sklearn.metrics.f1_score(y_lrnn_test, feature_logistic_prediction)
    
  print(confusion_matrix(y_lrnn_test, feature_logistic_prediction))
  print(model_type, "Accuracy:", feature_logistic_accuracy)
  print(model_type, "F1:", feature_logistic_F1_score)

print("-Competitiveness")
train_test_model(X_lrnn_train, y_lrnn_train, X_lrnn_test, y_lrnn_test, "Overall")
train_test_model(X_phoenix_train, y_phoenix_train, X_phoenix_test, y_phoenix_test, "Phoenix")
train_test_model(X_scottsdale_train, y_scottsdale_train, X_scottsdale_test, y_scottsdale_test, "Scottsdale")
train_test_model(X_mesa_train, y_mesa_train, X_mesa_test, y_mesa_test, "Mesa")
train_test_model(X_tempe_train, y_tempe_train, X_tempe_test, y_tempe_test, "Tempe")
train_test_model(X_maricopa_train, y_maricopa_train, X_maricopa_test, y_maricopa_test, "Maricopa")


-Race
[[692 418]
 [205 282]]
Overall Accuracy: 0.6098935504070131
Overall F1: 0.47514743049705144
[[298 203]
 [109 132]]
Phoenix Accuracy: 0.5795148247978437
Phoenix F1: 0.45833333333333337
[[110  58]
 [ 41  30]]
Scottsdale Accuracy: 0.5857740585774058
Scottsdale F1: 0.3773584905660377
[[90 71]
 [22 29]]
Mesa Accuracy: 0.5613207547169812
Mesa F1: 0.3841059602649006
[[82 47]
 [26 25]]
Tempe Accuracy: 0.5944444444444444
Tempe F1: 0.40650406504065045
[[93 62]
 [32 39]]
Maricopa Accuracy: 0.584070796460177
Maricopa F1: 0.4534883720930233


##Removing Peer Popularity

In [0]:
#'num_neighbours', 'entropy', 'competitiveness', 'peer_popularity'
def rate_data_split(peer_popularity_lr):
  X_lrnn_data = peer_popularity_lr.drop(['peer_popularity', 'rate_mid_2015'], axis = 'columns').to_numpy()
  y_lrnn_data = peer_popularity_lr['rate_mid_2015'].to_numpy()

  X_lrnn_data_processed = MinMaxScaler().fit_transform(X_lrnn_data)

  X_lrnn_train, X_lrnn_test, y_lrnn_train, y_lrnn_test = sklearn.model_selection.train_test_split(X_lrnn_data_processed, \
                                                                            y_lrnn_data, \
                                                                            test_size = 0.2) 
  oversample = RandomOverSampler(sampling_strategy='minority')                                                                  
  X_over, y_over = oversample.fit_resample(X_lrnn_train,y_lrnn_train)
  return X_over, X_lrnn_test, y_over, y_lrnn_test
  

X_lrnn_train, X_lrnn_test, y_lrnn_train, y_lrnn_test = rate_data_split(complete_data.copy())
X_phoenix_train, X_phoenix_test, y_phoenix_train, y_phoenix_test = rate_data_split(phoenix_complete_data.copy())
X_scottsdale_train, X_scottsdale_test, y_scottsdale_train, y_scottsdale_test = rate_data_split(scottsdale_complete_data.copy())
X_mesa_train, X_mesa_test, y_mesa_train, y_mesa_test = rate_data_split(mesa_complete_data.copy())
X_tempe_train, X_tempe_test, y_tempe_train, y_tempe_test = rate_data_split(tempe_complete_data.copy())
X_maricopa_train, X_maricopa_test, y_maricopa_train, y_maricopa_test = rate_data_split(maricopa_complete_data.copy())

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarni

In [0]:

def train_test_model(X_lrnn_train, y_lrnn_train, X_lrnn_test, y_lrnn_test, model_type):
  lr = [1.0]
  feature_logistic_accuracy = 0
  feature_logistic_F1_score = 0
  for i in range(len(lr)):
    feature_logistic = linear_model.SGDClassifier(loss = 'log', penalty = 'l1', learning_rate = 'adaptive', eta0 = lr[i], verbose=0)
    feature_logistic.fit(X_lrnn_train, y_lrnn_train)
    feature_logistic_prediction = feature_logistic.predict(X_lrnn_test)
    # print(feature_logistic_prediction)
    # print(y_lrnn_test)
    feature_logistic_accuracy = sklearn.metrics.accuracy_score(y_lrnn_test, feature_logistic_prediction)
    feature_logistic_F1_score = sklearn.metrics.f1_score(y_lrnn_test, feature_logistic_prediction)
    
  print(confusion_matrix(y_lrnn_test, feature_logistic_prediction))
  print(model_type, "Accuracy:", feature_logistic_accuracy)
  print(model_type, "F1:", feature_logistic_F1_score)

print("-Peer Popularity")
train_test_model(X_lrnn_train, y_lrnn_train, X_lrnn_test, y_lrnn_test, "Overall")
train_test_model(X_phoenix_train, y_phoenix_train, X_phoenix_test, y_phoenix_test, "Phoenix")
train_test_model(X_scottsdale_train, y_scottsdale_train, X_scottsdale_test, y_scottsdale_test, "Scottsdale")
train_test_model(X_mesa_train, y_mesa_train, X_mesa_test, y_mesa_test, "Mesa")
train_test_model(X_tempe_train, y_tempe_train, X_tempe_test, y_tempe_test, "Tempe")
train_test_model(X_maricopa_train, y_maricopa_train, X_maricopa_test, y_maricopa_test, "Maricopa")


-Race
[[656 455]
 [205 281]]
Overall Accuracy: 0.5867251095804634
Overall F1: 0.45990180032733224
[[294 215]
 [ 95 138]]
Phoenix Accuracy: 0.5822102425876011
Phoenix F1: 0.4709897610921502
[[120  53]
 [ 36  30]]
Scottsdale Accuracy: 0.6276150627615062
Scottsdale F1: 0.40268456375838924
[[79 68]
 [29 36]]
Mesa Accuracy: 0.5424528301886793
Mesa F1: 0.4260355029585799
[[77 42]
 [24 37]]
Tempe Accuracy: 0.6333333333333333
Tempe F1: 0.5285714285714286
[[74 80]
 [27 45]]
Maricopa Accuracy: 0.5265486725663717
Maricopa F1: 0.45685279187817257
